# version: 2
#  jobs:
#    build:
#      docker:
#        - image: circleci/ruby:2.4.1
#      steps:
#        - checkout
#        - run: echo "A first hello"
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
